------------------------------------------------------------
/usr/local/bin/pip3.4 run on Tue Aug  5 23:49:11 2014
Downloading/unpacking django-six
  Getting page https://pypi.python.org/simple/django-six/
  Could not fetch URL https://pypi.python.org/simple/django-six/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/django-six/ when looking for download links for django-six
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for django-six:
  * https://pypi.python.org/simple/django-six/
  Getting page https://pypi.python.org/simple/django-six/
  Could not fetch URL https://pypi.python.org/simple/django-six/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/django-six/ when looking for download links for django-six
  Could not find any downloads that satisfy the requirement django-six
Cleaning up...
  Removing temporary dir /tmp/pip_build_Twistory...
No distributions at all found for django-six
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python3.4/dist-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for django-six
